### ISSUE TITLE
M1 Mac Xcode12

### ISSUE THREAD

**Issue by msobo** [mfessenden/SKTiled#38]
On Xcode 12 - M1Mac i have trouble to set this Framework up as described.
with Carthage I get this error:

Building universal frameworks with common architectures is not possible. The device and simulator slices for "SKTiled" both build for: arm64
Rebuild with --use-xcframeworks to create an xcframework bundle instead.

cocoapods doesn't work either.

on Xcode 13 beta5 I tried to add the Framework directly via "File->Add Package" and pasted the GitHub link - still no luck, it was unable to resolve dependencies

im new to Xcode/iOS
please update install instructions for this framework

**Comment by mfessenden** [comment]
What's the command that you're running with carthage? I use this:

```sh
carthage update --use-xcframeworks
```
The resulting bundle will be in the `MyProject/Carthage/Build` directory. I then link the framework in Xcode in the **Frameworks, Libraries, and Embedded Content** group (you'll need to link it for each target that's using it):

<img width="676" alt="sktiled-xcfr-link" src="https://user-images.githubusercontent.com/911532/133434201-59801137-12ee-4dad-9f5a-2a80829822f5.png">

I prefer carthage because I can quickly test dev iterations of a framework with it. I don't use Cocoapods personally, so I'm not sure if it has a way to build binary frameworks.

If you'd like to build it yourself, here's a script I wrote for the beta of the next release. You'll need to run it from the **SKTiled** root directory, so if you save this into the `SKTiled/scripts` directory, run the command from the project root:

```sh
./scripts/build-xcframeworks.sh
```

Hope that helps, and good luck! 👍

```sh
#! /bin/sh
#
# Description:
#    This script creates a binary framework for use with all supported platforms & architectures.

HELP="

build-xcframeworks -- build binary frameworks script.

Usage:  build-xcframeworks [command]

Options (general):
  -h, --help      print help message.
  -c, --clean     clean the build directories on exit.
  -o, --output    xcframework output path.
"


# Release dir path
PROJECT_PATH=$PWD
BUILD_DIR=${PROJECT_PATH}/build
ARCHIVE_DIR=${BUILD_DIR}/archives
FRAMEWORKS_DIR=${PROJECT_PATH}/Frameworks
FRAMEWORK_FILE=${FRAMEWORKS_DIR}/SKTiled.xcframework


# parse arguments
CLEAN_BUILD_DIRS=0
PARAMS=""
while (( "$#" )); do
  case "$1" in
      -h|--help)
        printf '%s' "$HELP"
        exit 0
        shift
        ;;
    -c|--clean)
      CLEAN_BUILD_DIRS=1
      shift
      ;;
    -o|--output)
      if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
        OUTPUT_PATH=$2
        FRAMEWORK_FILE=${OUTPUT_PATH}/SKTiled.xcframework
        shift 2
      else
        echo "Error: Argument for $1 is missing" >&2
        exit 1
      fi
      ;;
    -*|--*=) # unsupported flags
      echo "Error: Unsupported flag $1" >&2
      exit 1
      ;;
    *) # preserve positional arguments
      PARAMS="$PARAMS $1"
      shift
      ;;
  esac
done

# set positional arguments in their proper place
eval set -- "$PARAMS"

# remove the build dir if it exists
if [ -d $BUILD_DIR ]
then
  rm -rf $BUILD_DIR
fi

# remove the output file if it already exists
if [ -d $FRAMEWORK_FILE ]
then
  rm -rf "$FRAMEWORK_FILE"
fi


mkdir $BUILD_DIR
mkdir $ARCHIVE_DIR

if [ ! -d $FRAMEWORKS_DIR ]
then
  mkdir $FRAMEWORKS_DIR
fi


# archive the various platforms...
xcodebuild archive \
-project SKTiled.xcodeproj \
-scheme SKTiled-macOS \
-destination "generic/platform=macOS" \
-archivePath ${ARCHIVE_DIR}/SKTiled-macOS \
SKIP_INSTALL=NO \
BUILD_LIBRARY_FOR_DISTRIBUTION=YES | xcpretty


xcodebuild archive \
-project SKTiled.xcodeproj \
-scheme SKTiled-iOS \
-destination "generic/platform=iOS" \
-archivePath ${ARCHIVE_DIR}/SKTiled-iOS \
SKIP_INSTALL=NO \
BUILD_LIBRARY_FOR_DISTRIBUTION=YES | xcpretty


xcodebuild archive \
-project SKTiled.xcodeproj \
-scheme SKTiled-iOS \
-destination "generic/platform=iOS Simulator" \
-archivePath ${ARCHIVE_DIR}/SKTiled-iOS-Sim \
SKIP_INSTALL=NO \
BUILD_LIBRARY_FOR_DISTRIBUTION=YES | xcpretty


xcodebuild archive \
-project SKTiled.xcodeproj \
-scheme SKTiled-tvOS \
-destination "generic/platform=tvOS" \
-archivePath ${ARCHIVE_DIR}/SKTiled-tvOS \
SKIP_INSTALL=NO \
BUILD_LIBRARY_FOR_DISTRIBUTION=YES | xcpretty


xcodebuild archive \
-project SKTiled.xcodeproj \
-scheme SKTiled-tvOS \
-destination "generic/platform=tvOS Simulator" \
-archivePath ${ARCHIVE_DIR}/SKTiled-tvOS-Sim \
SKIP_INSTALL=NO \
BUILD_LIBRARY_FOR_DISTRIBUTION=YES | xcpretty


# create the xcframework
xcodebuild -create-xcframework \
-framework ${ARCHIVE_DIR}/SKTiled-macOS.xcarchive/Products/Library/Frameworks/SKTiled.framework \
-framework ${ARCHIVE_DIR}/SKTiled-iOS.xcarchive/Products/Library/Frameworks/SKTiled.framework \
-framework ${ARCHIVE_DIR}/SKTiled-iOS-Sim.xcarchive/Products/Library/Frameworks/SKTiled.framework \
-framework ${ARCHIVE_DIR}/SKTiled-tvOS.xcarchive/Products/Library/Frameworks/SKTiled.framework \
-framework ${ARCHIVE_DIR}/SKTiled-tvOS-Sim.xcarchive/Products/Library/Frameworks/SKTiled.framework \
-output ${BUILD_DIR}/SKTiled.xcframework | xcpretty


# move the resulting framework to the output directory
mv ${BUILD_DIR}/SKTiled.xcframework $FRAMEWORK_FILE

if [ -d $FRAMEWORK_FILE ]
then
  echo "▪︎ writing xcframework to '${FRAMEWORK_FILE}'"
else
    echo "Error creating framework file '${FRAMEWORK_FILE}'"
    exit 1
fi

# cleanup build directory on exit
if [ $CLEAN_BUILD_DIRS = 1 ]
then
  echo "▪︎ cleaning up archives '${BUILD_DIR}'"
  rm -rf "$BUILD_DIR"
fi

```

**Comment by msobo** [comment]
dear Fessenden,
in your "getting started"-section you only mentioned the command `carthage update `
(without --use--xcframeworks). With this addition it works, he's doing something. But

- im still not able to import SKTiled inside my GameScene.swift file like im importing SpriteKit .. so when im trying to setup a scene like its written in the documentation "Scene Setup" I get an error with the very first definition of **`var tilemap: SKTilemap! (Cannot find type 'SKTilemap' in scope)`** 
- besides I get this error when I try to run my project where I tried to import your framework: **`Building for iOS Simulator, but the linked and embedded framework 'SKTiled.framework' was built for iOS.`**
- and another thing to mention: the 1.30b1 version inside the Carthage file is not working (no valid version error when I try to run it) - it only worked with the 1.22

Maby I don't fully understand how to import Frameworks correctly, what I did:
- I Downloaded the whole SKTiled.zip from Github
- I opened the project and on the right side of the build button I chose SKTiled-iOS - anyiOSDevice(arm64)
- i pressed build and after that the SKTiled.framework (in the products folder inside Xcode..) turned from red to black 
- I created a new SwiftUI Project in another window. inside the projects settings in the target section - "General"-Tab and dragged that SKTiled.framework to the general tab/Framewoks,Libaries,EmbeddedContent Section -> this finally created a new Folder "Frameworks" with the SKTiled.framework inside it
- then I closed Xcode and created that Carthage file inside the new projects folder and run you command carthage update --use-xcframeworks - but after all that still not able to use the framework

I couldn't find a clear explanation on how to import frameworks inside a project manually

**Comment by mfessenden** [comment]
Here's how I would approach this:

1. create a file named `Cartfile` in the root of your project. Add a reference to SKTiled:`github "mfessenden/SKTiled" ~> 1.2`
2. in a shell, browse to your project's root directory and run `carthage update --use-xcframeworks`
3. open your project in Xcode, select a target and select the **General** tab. Navigate to the `Carthage/Build` directory and drag `SKTiled.xcframework` into the **Frameworks, Libraries, and Embedded Content** section (alternatively, you can click the ➕button and browse to the framework)
4. import the framework with `import SKTiled` wherever needed

Once the framework is built and linked, you can select it in Xcode and verify where the file lives:

![sktiled-linked](https://user-images.githubusercontent.com/911532/133494662-51efd0d7-bedc-4885-bcfe-9f7e5ffcdc17.png)

Once you've linked the framework, you can quickly iterate versions of the framework (say if you create a fork specific to your needs) by running the carthage command.

**Comment by msobo** [comment]
Superb! that worked for me!
Thanks so much for your help and doing/sharing your work, awesome :)
